package job02;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class App extends Application {
    public static void main(String[] args) {
        launch();
    }

    @Override
    public void start(Stage stage) {
        stage.setTitle("Ma fenêtre");

        BorderPane conteneur = new BorderPane();

        Button boutonQuitter = new Button("Quitter");
        boutonQuitter.setOnAction(e -> System.exit(0));

        conteneur.setBottom(boutonQuitter);

        Scene scene = new Scene(conteneur, 500, 500);
        stage.setScene(scene);
        stage.show();
    }
}

